name: Trigger auto deployment for hive-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hive-backend-AutoDeployTrigger-b188c563-acb1-47ed-a789-f65fa7c36e92.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HIVEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HIVEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HIVEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: hiveacr3.azurecr.io
          registryUsername: ${{ secrets.HIVEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HIVEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: hive-backend
          resourceGroup: hive-rg
          imageToBuild: hiveacr3.azurecr.io/hive-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


